name: thesection
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.5
  connectivity_plus: ^2.2.0
  animations: ^2.0.2
  firebase_core: ^1.6.0
  cloud_firestore: ^3.1.10
  hive: ^2.0.5
  font_awesome_flutter: ^9.2.0
  image_picker: ^0.8.4+5
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.2
  hydrated_bloc: ^8.0.0 
  equatable: ^2.0.3
  firebase_storage: ^10.2.9
  universal_platform: ^1.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
