// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHo7LCAFiW6dPlgU2GSJ5Fj1M9iWsaCY',
    appId: '1:850967190716:web:65d7d7794bba7f28d144b9',
    messagingSenderId: '850967190716',
    projectId: 'thesection',
    authDomain: 'thesection.firebaseapp.com',
    storageBucket: 'thesection.appspot.com',
    measurementId: 'G-SR1SRG5N9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN261GReVsME5sqK9PpHKFNW8tX3pJntI',
    appId: '1:850967190716:android:6a92e9cfa0289d20d144b9',
    messagingSenderId: '850967190716',
    projectId: 'thesection',
    storageBucket: 'thesection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALXNhoVvCgpVRxS4X8l7UqwNC_FCYCTL8',
    appId: '1:850967190716:ios:40ae3a2a8c40967ed144b9',
    messagingSenderId: '850967190716',
    projectId: 'thesection',
    storageBucket: 'thesection.appspot.com',
    iosClientId:
        '850967190716-it6np58e2fjajheg4a5ckqkt5vp13e93.apps.googleusercontent.com',
    iosBundleId: 'com.thesection.app',
  );
}
